// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#define threads_x 64
#define threads_y 1
#define threads_z 1

int startIndex;
float4x4 localToObject;
int currentAmountBlades;

StructuredBuffer<float4> SharedGrassData;
RWStructuredBuffer<float4> grassDataA;
RWStructuredBuffer<float4> grassDataB;
RWStructuredBuffer<float4> grassDataC;

[numthreads(threads_x,threads_y,threads_z)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	//grassData[id.x]
}
