// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

int startIndex;
float4x4 patchMatrix;
int currentAmountBlades;

StructuredBuffer<float4> SharedGrassData;
RWStructuredBuffer<float4> grassDataA;
RWStructuredBuffer<float4> grassDataB;
RWStructuredBuffer<float4> grassDataC;

[numthreads(64,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	// TODO: insert actual code here!
}
